### ISSUE TITLE
Memory leaks when opening a large number of connections

### ISSUE THREAD

**Issue by cortelf** [fakefloordiv/indigo#48]
**To Reproduce**
1. `cd examples/helloworld`
2. `go run .`
3. `wrk -t12 -c900 -d1s http://<yourip>:9090/`
4. Repeat step 3 many times
5. See the huge amount of occupied memory in the Task Manager

**Expected behavior**
The memory must be cleared after closing connections

**My testing environment**
 - Windows 22H2 (go)
 - WSL 2 (wrk)

**Comment by fakefloordiv** [comment]
MacOS Monterey 12.4, same issue

**Comment by fakefloordiv** [comment]
Fixed. Thank you for reporting
